### ISSUE TITLE
Error when running using Python 3.11.1

### ISSUE THREAD

**Issue by Homailot** [EvanKepner/mutatest#38]
This error occurred when I tested my project using Python 3.11.1 and mutatest 3.1.0, with the following command `mutatest -t "python -m pytest"`.

```py
Traceback (most recent call last):
  File ".../src/backend/venv/bin/mutatest", line 8, in <module>
    sys.exit(cli_main())
             ^^^^^^^^^^
  File ".../src/backend/venv/lib/python3.11/site-packages/mutatest/cli.py", line 731, in cli_main
    main(args)
  File ".../src/backend/venv/lib/python3.11/site-packages/mutatest/cli.py", line 779, in main
    results_summary = run.run_mutation_trials(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "..../src/backend/venv/lib/python3.11/site-packages/mutatest/run.py", line 609, in run_mutation_trials
    mutation_sample_dispatch(
  File ".../src/backend/venv/lib/python3.11/site-packages/mutatest/run.py", line 530, in mutation_sample_dispatch
    current_mutation = random.sample(mutant_operations, k=1)[0]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.pyenv/versions/3.11.1/lib/python3.11/random.py", line 436, in sample
    raise TypeError("Population must be a sequence.  "
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```

I realize that this package does not support Python 3.11.1, however, the fix for this should be as simple as converting the mutant_operations set to a list using list().

**Comment by Homailot** [comment]
Ah, i see this has been addressed already, closing the issue

**Comment by bbelderbos** [comment]
Where was this addressed please? I still have to manually do this when pip installing mutatest (update: fixing on own fork as well as coverage update)
